### ISSUE TITLE
Image upload failed and cant find the uploaded images

### ISSUE THREAD

**Issue by muguMugunthan** [kaushikjadhav01/Online-Food-Ordering-Web-App#3]
Warning: Undefined array key "image" in C:\xampp\htdocs\Online-Food-Ordering-Web-App-master\account\index.php on line 220

**Comment by Graphicshub254** [comment]
> Warning: Undefined array key "image" in C:\xampp\htdocs\Online-Food-Ordering-Web-App-master\account\index.php on line 220

What does the line say

**Comment by kaushikjadhav01** [comment]
This is fixed now.
